title: Páraic Bradley
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring game developer on track to graduate MComp Computer Science with Games Engineering with a first class degree in June 2023. 
  <br><br>
  An experienced programmer with a fascination for all aspects of game design and a passion for exploring the possibilities of interactive storytelling. 
  <br><br>
  Portfolio is always being updated, so check back to take a look at what I've been working on recently.  
  <br><br>
  <a href="https://www.linkedin.com/in/paraic-bradley">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
